export type IconName = 
    | 'circle' 
    | 'download' 
    | 'info' 
    | 'safe-success' 
    | 'safe-warn' 
    | 'success' 
    | 'success-circle'
    | 'success-no-circle'
    | 'waiting'
    | 'waiting-circle'
    | 'warn'
    | 'info-circle'
    | 'cancel'
    | 'search'
    | 'clear'
    | 'back'
    | 'delete'
    | 'success-no-circle-thin'
    | 'arrow'
    | 'arrow-bold'
    | 'back-arrow'
    | 'back-arrow-thin'
    | 'close'
    | 'close-thin'
    | 'back-circle'

export type IconType = 
    | 'success'