import Vue from 'vue';

export class Actionsheet extends Vue {}
export class Agree extends Vue {}
export class Alert extends Vue {}
export class Badge extends Vue {}
export class Blur extends Vue {}
export class Box extends Vue {}
export class ButtonTab extends Vue {}
export class ButtonTabItem extends Vue {}
export class Calendar extends Vue {}
export class Card extends Vue {}
export class Cell extends Vue {}
export class CellBox extends Vue {}
export class CellFormPreview extends Vue {}
export class Checker extends Vue {}
export class CheckerItem extends Vue {}
export class CheckIcon extends Vue {}
export class Checklist extends Vue {}
export class Clocker extends Vue {}
export class ColorPicker extends Vue {}
export class Confirm extends Vue {}
export class Countdown extends Vue {}
export class Countup extends Vue {}
export class Datetime extends Vue {}
export class DatetimeRange extends Vue {}
export class DatetimeView extends Vue {}
export class Demobasic extends Vue {}
export class Demoindex extends Vue {}
export class DevTip extends Vue {}
export class Divider extends Vue {}
export class Drawer extends Vue {}
export class Flexbox extends Vue {}
export class FlexboxItem extends Vue {}
export class Flow extends Vue {}
export class FlowLine extends Vue {}
export class FlowState extends Vue {}
export class FormPreview extends Vue {}
export class Fullpage extends Vue {}
export class Grid extends Vue {}
export class GridItem extends Vue {}
export class Group extends Vue {}
export class GroupTitle extends Vue {}
export class Icon extends Vue {}
export class InlineCalendar extends Vue {}
export class InlineDesc extends Vue {}
export class InlineLoading extends Vue {}
export class InlineXNumber extends Vue {}
export class InlineXSwitch extends Vue {}
export class Loading extends Vue {}
export class LoadMore extends Vue {}
export class Marquee extends Vue {}
export class MarqueeItem extends Vue {}
export class Masker extends Vue {}
export class Msg extends Vue {}
export class NumberRoller extends Vue {}
export class Panel extends Vue {}
export class Picker extends Vue {}
export class Popover extends Vue {}
export class Popup extends Vue {}
export class PopupHeader extends Vue {}
export class PopupPicker extends Vue {}
export class PopupRadio extends Vue {}
export class Previewer extends Vue {}
export class Qrcode extends Vue {}
export class Radio extends Vue {}
export class Range extends Vue {}
export class Rater extends Vue {}
export class Scroller extends Vue {}
export class Search extends Vue {}
export class Selector extends Vue {}
export class Shake extends Vue {}
export class Spinner extends Vue {}
export class Step extends Vue {}
export class StepItem extends Vue {}
export class Sticky extends Vue {}
export class Swipeout extends Vue {}
export class SwipeoutButton extends Vue {}
export class SwipeoutItem extends Vue {}
export class Swiper extends Vue {}
export class SwiperItem extends Vue {}
export class Tab extends Vue {}
export class Tabbar extends Vue {}
export class TabbarItem extends Vue {}
export class TabItem extends Vue {}
export class Timeline extends Vue {}
export class TimelineItem extends Vue {}
export class Tip extends Vue {}
export class Toast extends Vue {}
export class Video extends Vue {}
export class ViewBox extends Vue {}
export class WechatEmotion extends Vue {}
export class WeekCalendar extends Vue {}
export class WepayInput extends Vue {}
export class XAddress extends Vue {}
export class XButton extends Vue {}
export class XCircle extends Vue {}
export class XDialog extends Vue {}
export class XHeader extends Vue {}
export class XHr extends Vue {}
export class XImg extends Vue {}
export class XInput extends Vue {}
export class XNumber extends Vue {}
export class XProgress extends Vue {}
export class XSwitch extends Vue {}
export class XTable extends Vue {}
export class XTextarea extends Vue {}