server {
    listen 8080;
    server_name _;

    location = /healthz {
        access_log off;
        return 200 "ok\n";
    }

    location / {
        return 301 https://doc.vux.li$request_uri;
    }
}
